name: internship-watcher

on:
  schedule:
    # UTC; every 30 min
    - cron:  "*/30 * * * *"
  workflow_dispatch: {}          # allows manual “Run workflow” button

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run watcher
        env:                       # pass GH secrets -> env vars
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT:   ${{ secrets.SMTP_PORT }}
          SMTP_USER:   ${{ secrets.SMTP_USER }}
          SMTP_PASS:   ${{ secrets.SMTP_PASS }}
          EMAIL_FROM:  ${{ secrets.EMAIL_FROM }}
          EMAIL_TO:    ${{ secrets.EMAIL_TO }}
        run: |
          python watcher.py
